### PR TITLE
Copy to system

### PR DESCRIPTION
**Pull request by Smurph82**
I have added the ability that if the app is installed in /data/app for it to be moved to /system/app. A reboot is currently required for this to work. I have tried to follow your coding style and added all icons that I used that match the size of the icons you had created. The icons were pulled form the Android SDK. If you keep this feature feel free to change the icons. I have made it so if the app is installed in /system/app then this option will not appear in the setting, only if the app is in /data/app.

### CODE REVIEW

**Comment by koush** [comment]
Hi, I appreciate the commit, but it can not be in the Settings Fragment.

This is because this Superuser is already ROM embedded in CM and AOKP, and they wouldn't want that setting/option as it is already Settings embedded.

Furthermore, it should copy itself to /system as part of the normal (non recovery) install process. /system is mounted as read-write there anyways. I think that is the right place to do it.

**Comment by koush** [comment]
Another comment I wanted to make: the recovery install process installs it as a System app, so I'm not sure how necessary this is.

**Comment by Smurph82** [comment]
I completely understand about the embedded part I had not even thought about that. 

But I have to say that you lost me a little bit on the second part. If you help me with a place to move that function then I will try to get it moved. Are you suggesting that when the app is installed from the play store, default to /data/app, then when the app is starting it run a check to see where it is installed and then gives the option for the user to move it to /system, or ignore on start up from now on.

**Comment by Smurph82** [comment]
This was mainly for when the app is installed from the play store then the user wants to move it to the system. All update are installed to /data/app this would give the ability to move the update into the /system/app

Edit:
I know the recovery installs to the system. It was a pain testing this over and over again. reboot after reboot after reboot. I am sure you have been there.

**Comment by Smurph82** [comment]
What if I the user installs this from the play store over another Superuser app. You currently check for your version of the su binary. At that point if the user wants to install your su then we have the app remove the other Superuser.apk and binary install your binary and at that time move your Superuser into the /system followed by a reboot

**Comment by Smurph82** [comment]
Do you think that this is a usable feature or should I drop it?

**Comment by koush** [comment]
Yeah, it's a usable feature. If you follow the git history, I actually tried to implement it myself, but there's a lot of "gotchas" involved. :) The annoying app restart being one of them...
That's the only reason I did not implement it myself.

As I said, I think if you simply copy (instead of move) it to /system during su binary install (MainActivity.java), I think you can forego the reboot.

**Comment by ogr3** [comment]
I agree it would be a very nice feature, but it seems to be a bit tricky to implement.

Today you either install through recovery (basically the same effect as flashing the zip). Needs a reboot into recovery (needs a custom recovery installed).

Or you do the normal install and move the app to /system/app with Titanium Backup or similiar tool. You don't need the reboot, but the icon will disappear if you have a shortcut. If the app would copy itself to /system you would need to restart the app and remove the copy in /data I guess?

**Comment by Smurph82** [comment]
Thanks deleting this branch I will work of a different approach.

**Pull request closed without merging**
