### PR TITLE
Several changes

### PR DESCRIPTION
**Pull request by BILLyTheLiTTle**
I developed some features that I would like to have at the application. 
In some commits you can see that I did things that you don't like (let's say deactivating the countdown as su resquest!), but in others you can find changes that I believe are useful (actions on lock-click at an application).

### CODE REVIEW

**Comment by koush** [comment]
Hi, please submit this to CyanogenMod gerrit. This looks good, but I'm sure there will be a lot of feedback.

**Comment by BILLyTheLiTTle** [comment]
Sure I will submit code there. But I am viewing 3 branches.
The "master" branch is behind the "master" branch in github.
So I have some questions!
1. At which branch would you like to commit these changes at gerrit?
2. Should I remove the local copy of the github repo and start working only at gerrit?

**Comment by koush** [comment]
cm-10.2 branch

**Comment by BILLyTheLiTTle** [comment]
All changes are uploaded for review. I added you as a reviewer. If there is anything else I could do let me know (Add more reviewers, etc).

**Comment by koush** [comment]
Where is the lock-click app commit? What does that do?

**Comment by BILLyTheLiTTle** [comment]
Hello,

I don't understand what do you mean when saying "lock-click app commit".But as I understand you want the long click app commit. I have abandoned some commits because I found them really hard to be understood. I made over my branches and commits and I will not upload a fleet of commits again. Sorry for the inconvinience but I beleive this is better for the reviewers and for me to correct the source according to reviewers comments.

**Pull request closed without merging**
