### PR TITLE
daemon: Send FDs over socket, reuse existing terminal.

### PR DESCRIPTION
**Pull request by mkasick**
Now sends remote file descriptors (stdin, etc.) across socket directly,
instead of pumping data through FIFOs.

Steals and reuses the existing terminal on stdin, if one exists, instead of
creating a new pty.

Warning: Reuse of existing terminal breaks job control in the caller shell.

### CODE REVIEW

**Comment by mkasick** [comment]
I'm not really expecting this to be merged as-is, but see it as a starting point for cleaning up the fd and tty issues with the daemon.

The one issue with stealing and reuisng the existing terminal is that it breaks job control when returning to the caller shell, since the caller session has lost control of the terminal.  Honestly that's not something I'm particularly concerned about as the typical model of using su on an terminal session is at least figuratively, if not literally an "exec su".

Furthermore, a [one-line patch](https://github.com/mkasick/android_external_mksh/commit/297c472e40df5fb1c3790e03401bdafb3317b381) to mksh will reacquire the controlling terminal after a job if lost, and I'd expect a similar fix could be made for BusyBox's shell.

That said, a cleaned-up pty proxy would have the benefit of "just working" in all scenarios, though I might still prefer to have the pty-less version available as a switch option to avoid compatibility issues.

**Comment by tan-ce** [comment]
Some of the scripts I have on my tablet rely on su returning and the terminal being available after the su called is terminated. (eg. I have a chroot script that has some clean up after the chrooted shell terminates. Other times, I launch my chroot and expect to return to the original shell when it terminates.)

To clarify, when you mention a pty proxy, do you mean that a new pty is created, or you'll somehow reused the current terminal TTY?

**Comment by mkasick** [comment]
So both the caller shell and terminal are functional after su exits.  It's just that in an unpatched shell, job control features do not work.  So, after su exits, you can't control-c (SIGINT), control-z (SIGTSTP), or control-\ (SIGQUIT), but the shell is still operational, can run commands, can complete executing a script, and can read/write to the terminal.

Of course, job control features do work in subsequent su shells since the controlling terminal is reacquired.  They also work fine in a patched shell, or if you close and reopen the terminal emulator.

By "pty proxy", I mean creating a new pty that's used by the su shell and piping its contents and control back and forth with the original terminal.

Personally, my issue with pty proxies is that they tend to exhibit suble bugs.  The ones implemented by ssh, screen, and tmux are quite sophisticated.  The one implemented by adb has issues with window resize events and some other things I've ran into in the past.  I like the idea of trying to retain as much of the semantics and behavior of non-daemon su as possible, and I think in the case of CyanogenMod shipping patched mksh and busybox to fix the job control issue is quite doable.  Otherwise I'm not opposed to a pty proxy if there's at least the option to turn it off.

**Comment by tan-ce** [comment]
Thanks for the explanation. Regarding pty proxies, at least for the pull
request I made, the handling was based on my reading SSH's source code. The
tricky part seems to be setting up stdin properly. Although one remaining
issue occurs when apps try to directly open /dev/tty, especially when used
at the end of a pipe, but this doesn't affect fully interactive shells or
when su is called by another process.

Still, I suppose my concern is because I would rather not have to require
patches in other projects. But, as you mentioned, all these could be made
options. I'll probably wait and see which direction koush prefers to take
his project in.

**Comment by koush** [comment]
I really like this, as it removes a ton of extra code. My concern, that you described, is that it will require patches to external apps. That's not really an option, as remember that a lot of users are using this as stock + root, and using whatever default "sh" binary ships on their device. Any thoughts on that?

**Comment by tan-ce** [comment]
If we're discussing the case where we're not using send_fd for an interactive terminal, this would work without requiring patching the shell if we can prevent the daemon end from grabbing the FD to become the controlling TTY, which if I'm not mistaken mainly involves not doing a TIOCSCTTY.

But if we want to do this for interactive shells without patching the shell, we'd basically have to do what reptyr (https://github.com/nelhage/reptyr) does after the root shell terminates, so it is possible...

**Comment by mkasick** [comment]
I wouldn't go as far as to say it _requires_ patches to external apps.  It's true, there's a strict loss of functionality in unmodified shells, but I don't really see that being a problem in practice.  At least, it's a total non-issue for the way I use su shells and I would imagine it's the same for most folks.  Likely the biggest issue is that the shell _complains_ on su's exit that it doesn't have a controlling terminal, and that user-visible complaint is something that's likely to come up.

I also don't see having to patch external shells being a big problem.  Daemonized su already requires init.rc modifications, so the level of invasiveness already exceeds "flash Superuser.zip".  Conversely, I'm not aware of OEMs regularly making changes to mksh, so including a source-built version in modified OEM ROMs is entirely feasible.

That said, I do agree it would be _nice_ to support unmodified shells with no errors/warnings/loss of functionality.  We would have to implement a solid pty proxy to do that.  Or code injection as reptyr does, but I think that's even more difficult.  Either way, it's a good bit of code.

If we're willing to hash out a "good enough" pty proxy, as tan-ce has been working on, perhaps the solution would be to use a pty proxy by default but allow it to be turned off with a system property.  That way, ROMs (e.g., CM) that ship with patched shells can set the property and use a pty-proxy-less su for maximum compatibility/efficiency.

**Comment by koush** [comment]
Merged @tan-ce stuff. closing this.

**Pull request closed without merging**
