### PR TITLE
slovak translation updated

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by koush** [comment]
@pylerSM This needs to be submitted to CyanogenMod gerrit. Please read the README

**Comment by pylerSM** [comment]
Ouch, i have never worked with gerrit :/ okey, i will try look on it..

**Comment by pylerSM** [comment]
hmm.. i looked on it. its too difficult for me. so sad :((

**Comment by therbom** [comment]
http://review.cyanogenmod.org/#/c/34071

**Comment by pylerSM** [comment]
Thanks. Nice ...

**Pull request merged**
