### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by jchleb**
changes only in strings.xml, 2 other files are same as English source.

### CODE REVIEW

**Comment by koush** [comment]
thanks! but hold off a bit, as the resources are still in _heavy_ flux. lot left to be done!

**Comment by jchleb** [comment]
you're welcome.
no problem, I'll keep committing to my repo, and when you'll be ready I'll
pull request that all at once.

2013/2/18 Koushik Dutta notifications@github.com

**Comment by koush** [comment]
cool, i'm just saving you the trouble, as I imagine even the existing resources will change quite a bit, and may cause you extra work

**Comment by koush** [comment]
Hey, I'm ready for translations now. Can you remove the styles.xml and dimens.xml from your pull though?

**Comment by jchleb** [comment]
Hi,
I'm currently on holidays and I have a very weak Internet access, no way to
use github.

If you need it quickly, please reply and attach your EN strings.xml, I'll
try to send it back to you asap.
If there is no hurry, I'll make a pull on Sunday when returned back home.

**Comment by jchleb** [comment]
Hi,
Here is a first Fr version for Superuser.

**Pull request merged**
