### PR TITLE
gen added to gitignore and gen folder removed 

### PR DESCRIPTION
**Pull request by anupcowkur**

### CODE REVIEW

**Comment by koush** [comment]
NooooOOOOOO http://stackoverflow.com/questions/893913/should-i-store-generated-code-in-source-control/893934#893934

**Comment by anupcowkur** [comment]
In the same thread: http://stackoverflow.com/a/893946/1369222

But it's your call. 

What else can I do to help?

**Comment by koush** [comment]
@anupcowkur I agree it is a matter of opinion. gen files in Android, at least, are deterministically generated, so there's no need to "check in every build", unless a there is a resource change. In which case, you'd have to check in anyways.

**Comment by koush** [comment]
Also, I detail more why I do this on Google+, as my pedantic checking in of gen files helped me locate an otherwise elusive bug:

https://plus.google.com/u/0/103583939320326217147/posts/QUhhq1kPFEn

**Comment by anupcowkur** [comment]
Nothing proves a point like a real world use case. I guess you are right.

**Pull request closed without merging**
