### PR TITLE
Translation updates

### PR DESCRIPTION
**Pull request by raziel23x**
Japanese and Korean updates

### CODE REVIEW

**Comment by koush** [comment]
This seems to have completely changed the files... did you change the encoding?

**Comment by koush** [comment]
Also, translations should be submitted to CyanogenMod's gerrit, as that has a very well structured submission process. If you are unfamiliar with that process I think @therbom can assist you.

**Comment by raziel23x** [comment]
The gerret completely confuses me and I used notepad++ to do the edits
using Github windows app

**Comment by therbom** [comment]
I have sent an email about this to our Japanese and Korean translator(s).

**Comment by chanhee0222** [comment]
Hello, raziel23x.
I've checked your Korean translation update, but all of the translations are incorrect and doesn't make sense.
It seems you used some kind of translation software. Please do not submit translations done by machine.

**Pull request closed without merging**
