### PR TITLE
Turkish translation

### PR DESCRIPTION
**Pull request by kyraxyg**
Turkish translation. I have compiles as a part of paranoidandroid rom and tested on my nexus 4.

### CODE REVIEW

**Comment by koush** [comment]
submit translations to CM gerrit please!

**Comment by kyraxyg** [comment]
if only i can. i will try as i have translated as a part of paranoidandroid rom, it might be troublesome. And the thing is i don't think anybody will ever approve in the gerrit.

**Comment by koush** [comment]
@therbom take a look please

**Comment by kyraxyg** [comment]
While i was trying i see the superuser in the CM git already has turkish translation altough there are some mistakes here and there but it is good enough . As paranoid uses koush/superuser in its manifest, there seems no translation. So can you kindly pull the turkish translation from cm repo

**Comment by kyraxyg** [comment]
I have spesifically submitted for the master branch as paranoidandroid uses koush/superuser master branch.

**Comment by therbom** [comment]
As far as I know the master branch is not used in CM. Please push your
improvements to the cm-10.1 and cm-10.1-staging branch and also add the
author of the original translations, Oguz Kirat I believe, to your change.
Op 22 jun. 2013 01:26 schreef "kyraxyg" notifications@github.com het
volgende:

**Comment by kyraxyg** [comment]
The translation i pushed to master branch is not a revision of Oguz Kırat's rather it is a new one done by me while i was compiling paranoidandroid rom. As far as i am concerned i don't want to push the translation to cm-10.1 branch as it has a rather well translation. Paranoid android rom uses koush/Superuser git branch master so i wanted to translate for paranoid.
As a solution;
1. The translation i have made to master branch gets pulled and koush pull the change to his repo.
2. The translation in cm-10.1 branch gets pulled to koush master branch and i abandon my translation and work on improving Oguz's if neccessary.
3.Koush acceptes the github pull request for my translation and i abandon my translation in gerrit.

**Comment by koush** [comment]
I have pulled CM's latest changes into this repository.

All the translation changes I access are from CM gerrit only. I do not have the knowledge to guarantee the quality of the translations, and defer to the CM translation team in that regard.

If Paranoid Android is using my Superuser, then the changes I just pulled should give you the CM turkish translations in their next build.

**Comment by kyraxyg** [comment]
thanks you.
the translation in cm is good enough. There are some writing errors but it is minor. If i have time i may fix it.

**Pull request closed without merging**
